# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kde5-powerdevil

# >> macros
# << macros

Summary:    Manages the power consumption settings of a Plasma Shell
Version:    4.97.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kde5-powerdevil.yaml
Source101:  kde5-powerdevil-rpmlintrc
Patch0:     remove-useless-xcb-modules.patch
Requires:   kde5-filesystem
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  pkgconfig(Qt5X11Extras)
BuildRequires:  pkgconfig(systemd)
BuildRequires:  pkgconfig(upower-glib)
BuildRequires:  pkgconfig(xcb)
BuildRequires:  pkgconfig(xrandr)
BuildRequires:  kde5-rpm-macros
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kf5-umbrella
BuildRequires:  kf5-kauth-devel
BuildRequires:  kf5-kidletime-devel
BuildRequires:  kf5-kconfig-devel
BuildRequires:  kf5-solid-devel
BuildRequires:  kf5-ki18n-devel
BuildRequires:  kf5-kglobalaccel-devel
BuildRequires:  kf5-kio-devel
BuildRequires:  kf5-kwindowsystem-devel
BuildRequires:  kf5-plasma-devel
BuildRequires:  kf5-knotifyconfig-devel
BuildRequires:  kf5-kdelibs4support-devel
BuildRequires:  kde5-plasma-workspace-devel
BuildRequires:  chrpath
Provides:   powerdevil = %{version}-%{release}
Conflicts:   kde-runtime
Conflicts:   powerdevil

%description
Manages the power consumption settings of a Plasma Shell.


%package kcm
Summary:    Power management configuration module for Plasma
Group:      System/Base
Requires:   %{name} = %{version}-%{release}

%description kcm
Power management configuration module for Plasma.


%prep
%setup -q -n %{name}-%{version}/upstream

# remove-useless-xcb-modules.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
%kde5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kde5_make_install
# << install pre

# >> install post
# Don't bother with -devel
rm -f %{buildroot}/%{_kde5_libdir}/libpowerdevil{configcommonprivate,core,ui}.so
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING
%{_kde5_sysconfdir}/dbus-1/system.d/org.kde.powerdevil.backlighthelper.conf
%{_kde5_libdir}/libpowerdevilconfigcommonprivate.so.*
%{_kde5_libdir}/libpowerdevilcore.so.*
%{_kde5_libdir}/libpowerdevilui.so.*
%{_kde5_libexecdir}/kauth/backlighthelper
%{_datadir}/dbus-1/system-services/org.kde.powerdevil.backlighthelper.service
%{_datadir}/knotifications5/powerdevil.notifyrc
%{_datadir}/polkit-1/actions/org.kde.powerdevil.backlighthelper.policy
%{_datadir}/kservices5/kded/*.desktop
# >> files
# << files

%files kcm
%defattr(-,root,root,-)
%{_kde5_plugindir}/*.so
%{_datadir}/kservices5/*.desktop
%{_datadir}/kservicetypes5/*.desktop
# >> files kcm
# << files kcm
